# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Nightly

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - run: dotnet build --configuration Release KSharpPlus/KSharpPlus.csproj -p:VersionSuffix='nightly-${{ github.run_number }}.${{ github.run_attempt }}' -p:BuildNumber="${{ github.run_number }}/${{ github.run_attempt }}"
    - name: Test
      run: dotnet test --verbosity normal KSharpPlus/KSharpPlus.csproj -p:VersionSuffix='nightly-${{ github.run_number }}.${{ github.run_attempt }}' -p:BuildNumber="${{ github.run_number }}/${{ github.run_attempt }}"
    - name: Create the package
      if: ${{ github.event_name == 'push' }}
      run: nuget pack KSharpPlus/KSharpPlus.csproj -properties Configuration=Release -properties VersionSuffix="nightly-${{ github.run_number }}.${{ github.run_attempt }}" -properties BuildNumber="${{ github.run_number }}/${{ github.run_attempt }}" -OutputDirectory KSharpPlus/bin/Release/
    - name: Publish the package to GPR
      if: ${{ github.event_name == 'push' }}
      run: dotnet nuget push KSharpPlus/bin/Release/*.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Upload Artifact
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v3
      with:
        name: KSharpPlus-Nightly-${{ github.run_number }}∕${{ github.run_attempt }}
        path: KSharpPlus/bin/Release/*
